import type {
  User,
  Institution,
  Workflow,
  Task,
  Label,
  ActivityItem,
  Notification,
  DashboardStats,
  TaskHistory,
} from '@/types'

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@institution.gov',
    institutionId: '1',
    institutionName: 'Department of Education',
    role: 'admin',
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@institution.gov',
    institutionId: '1',
    institutionName: 'Department of Education',
    role: 'manager',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@institution.gov',
    institutionId: '2',
    institutionName: 'Health Services',
    role: 'member',
  },
  {
    id: '4',
    name: 'James Wilson',
    email: 'james.wilson@institution.gov',
    institutionId: '1',
    institutionName: 'Department of Education',
    role: 'member',
  },
]

export const mockInstitutions: Institution[] = [
  {
    id: '1',
    name: 'Department of Education',
    type: 'Government Agency',
    active: true,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Health Services',
    type: 'Public Health',
    active: true,
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: '3',
    name: 'City Planning Office',
    type: 'Municipal',
    active: true,
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: '4',
    name: 'Transportation Authority',
    type: 'Infrastructure',
    active: false,
    createdAt: '2023-12-10T10:00:00Z',
  },
]

export const mockLabels: Label[] = [
  { id: '1', name: 'Urgent', color: 'oklch(0.55 0.22 25)' },
  { id: '2', name: 'High Priority', color: 'oklch(0.65 0.20 35)' },
  { id: '3', name: 'Review Required', color: 'oklch(0.55 0.15 200)' },
  { id: '4', name: 'Documentation', color: 'oklch(0.60 0.15 252)' },
  { id: '5', name: 'Legal Review', color: 'oklch(0.50 0.12 280)' },
]

export const mockWorkflows: Workflow[] = [
  {
    id: '1',
    name: 'Budget Approval',
    description: 'Process for approving department budgets',
    status: 'active',
    steps: [
      { id: '1', name: 'Submission', order: 1, allowedStatuses: ['todo', 'in-progress'] },
      { id: '2', name: 'Initial Review', order: 2, allowedStatuses: ['in-progress', 'review'] },
      { id: '3', name: 'Committee Review', order: 3, allowedStatuses: ['review', 'blocked'] },
      { id: '4', name: 'Final Approval', order: 4, allowedStatuses: ['review', 'completed'] },
    ],
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '2',
    name: 'Project Proposal',
    description: 'Workflow for new project proposals',
    status: 'active',
    steps: [
      { id: '5', name: 'Draft', order: 1, allowedStatuses: ['todo', 'in-progress'] },
      { id: '6', name: 'Technical Review', order: 2, allowedStatuses: ['in-progress', 'review'] },
      { id: '7', name: 'Budget Analysis', order: 3, allowedStatuses: ['review', 'blocked'] },
      { id: '8', name: 'Approval', order: 4, allowedStatuses: ['review', 'completed'] },
    ],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '3',
    name: 'Policy Review',
    description: 'Process for reviewing institutional policies',
    status: 'active',
    steps: [
      { id: '9', name: 'Research', order: 1, allowedStatuses: ['todo', 'in-progress'] },
      { id: '10', name: 'Draft Policy', order: 2, allowedStatuses: ['in-progress', 'review'] },
      { id: '11', name: 'Stakeholder Review', order: 3, allowedStatuses: ['review'] },
      { id: '12', name: 'Implementation', order: 4, allowedStatuses: ['in-progress', 'completed'] },
    ],
    createdAt: '2024-02-01T10:00:00Z',
  },
]

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Q2 2024 Budget Submission',
    description: 'Submit the Q2 budget proposal for the education department',
    workflowId: '1',
    workflowName: 'Budget Approval',
    currentStepId: '2',
    currentStepName: 'Initial Review',
    status: 'in-progress',
    assigneeId: '2',
    assigneeName: 'Michael Chen',
    creatorId: '1',
    institutionId: '1',
    dueDate: '2024-03-15T23:59:59Z',
    labels: [mockLabels[1], mockLabels[3]],
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-03-01T14:30:00Z',
  },
  {
    id: '2',
    title: 'New STEM Program Proposal',
    description: 'Develop proposal for new STEM education initiative',
    workflowId: '2',
    workflowName: 'Project Proposal',
    currentStepId: '6',
    currentStepName: 'Technical Review',
    status: 'review',
    assigneeId: '3',
    assigneeName: 'Emily Rodriguez',
    creatorId: '1',
    institutionId: '1',
    dueDate: '2024-03-20T23:59:59Z',
    labels: [mockLabels[2]],
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2024-03-05T09:15:00Z',
  },
  {
    id: '3',
    title: 'Student Privacy Policy Update',
    description: 'Review and update student data privacy policies',
    workflowId: '3',
    workflowName: 'Policy Review',
    currentStepId: '10',
    currentStepName: 'Draft Policy',
    status: 'in-progress',
    assigneeId: '4',
    assigneeName: 'James Wilson',
    creatorId: '2',
    institutionId: '1',
    dueDate: '2024-03-10T23:59:59Z',
    labels: [mockLabels[0], mockLabels[4]],
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-03-02T16:45:00Z',
  },
  {
    id: '4',
    title: 'Facility Maintenance Budget',
    description: 'Prepare annual facility maintenance budget proposal',
    workflowId: '1',
    workflowName: 'Budget Approval',
    currentStepId: '1',
    currentStepName: 'Submission',
    status: 'todo',
    assigneeId: '2',
    assigneeName: 'Michael Chen',
    creatorId: '1',
    institutionId: '1',
    dueDate: '2024-03-25T23:59:59Z',
    labels: [],
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
  },
  {
    id: '5',
    title: 'Teacher Training Program',
    description: 'Develop comprehensive teacher professional development program',
    workflowId: '2',
    workflowName: 'Project Proposal',
    currentStepId: '8',
    currentStepName: 'Approval',
    status: 'completed',
    assigneeId: '1',
    assigneeName: 'Sarah Johnson',
    creatorId: '3',
    institutionId: '1',
    dueDate: '2024-02-28T23:59:59Z',
    labels: [mockLabels[1]],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-02-27T11:20:00Z',
  },
  {
    id: '6',
    title: 'Health & Safety Guidelines',
    description: 'Update institutional health and safety guidelines',
    workflowId: '3',
    workflowName: 'Policy Review',
    currentStepId: '11',
    currentStepName: 'Stakeholder Review',
    status: 'blocked',
    assigneeId: '3',
    assigneeName: 'Emily Rodriguez',
    creatorId: '1',
    institutionId: '2',
    dueDate: '2024-03-05T23:59:59Z',
    labels: [mockLabels[0], mockLabels[2]],
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-03-03T13:10:00Z',
  },
  {
    id: '7',
    title: 'Technology Infrastructure Upgrade',
    description: 'Plan and budget for campus-wide technology infrastructure improvements',
    workflowId: '2',
    workflowName: 'Project Proposal',
    currentStepId: '5',
    currentStepName: 'Draft',
    status: 'in-progress',
    assigneeId: '4',
    assigneeName: 'James Wilson',
    creatorId: '2',
    institutionId: '1',
    dueDate: '2024-04-01T23:59:59Z',
    labels: [mockLabels[1], mockLabels[3]],
    createdAt: '2024-02-25T10:00:00Z',
    updatedAt: '2024-03-04T15:30:00Z',
  },
  {
    id: '8',
    title: 'Summer Program Budget Review',
    description: 'Review and approve summer educational program budgets',
    workflowId: '1',
    workflowName: 'Budget Approval',
    currentStepId: '3',
    currentStepName: 'Committee Review',
    status: 'review',
    assigneeId: '1',
    assigneeName: 'Sarah Johnson',
    creatorId: '2',
    institutionId: '1',
    dueDate: '2024-03-08T23:59:59Z',
    labels: [mockLabels[0]],
    createdAt: '2024-02-18T10:00:00Z',
    updatedAt: '2024-03-03T10:00:00Z',
  },
]

export const mockActivities: ActivityItem[] = [
  {
    id: '1',
    type: 'status_changed',
    message: 'changed status from In Progress to Review',
    taskId: '2',
    taskTitle: 'New STEM Program Proposal',
    userId: '3',
    userName: 'Emily Rodriguez',
    timestamp: '2024-03-05T09:15:00Z',
  },
  {
    id: '2',
    type: 'task_assigned',
    message: 'assigned to James Wilson',
    taskId: '7',
    taskTitle: 'Technology Infrastructure Upgrade',
    userId: '2',
    userName: 'Michael Chen',
    timestamp: '2024-03-04T15:30:00Z',
  },
  {
    id: '3',
    type: 'task_updated',
    message: 'updated due date',
    taskId: '3',
    taskTitle: 'Student Privacy Policy Update',
    userId: '4',
    userName: 'James Wilson',
    timestamp: '2024-03-02T16:45:00Z',
  },
  {
    id: '4',
    type: 'task_created',
    message: 'created new task',
    taskId: '4',
    taskTitle: 'Facility Maintenance Budget',
    userId: '1',
    userName: 'Sarah Johnson',
    timestamp: '2024-03-01T10:00:00Z',
  },
  {
    id: '5',
    type: 'status_changed',
    message: 'changed status from Review to Blocked',
    taskId: '6',
    taskTitle: 'Health & Safety Guidelines',
    userId: '3',
    userName: 'Emily Rodriguez',
    timestamp: '2024-03-03T13:10:00Z',
  },
]

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'deadline',
    message: 'Task "Student Privacy Policy Update" is due in 2 days',
    taskId: '3',
    taskTitle: 'Student Privacy Policy Update',
    read: false,
    createdAt: '2024-03-08T10:00:00Z',
  },
  {
    id: '2',
    type: 'assignment',
    message: 'You were assigned to "Technology Infrastructure Upgrade"',
    taskId: '7',
    taskTitle: 'Technology Infrastructure Upgrade',
    read: false,
    createdAt: '2024-03-04T15:30:00Z',
  },
  {
    id: '3',
    type: 'mention',
    message: 'Sarah Johnson mentioned you in a comment',
    taskId: '2',
    taskTitle: 'New STEM Program Proposal',
    read: true,
    createdAt: '2024-03-03T14:20:00Z',
  },
  {
    id: '4',
    type: 'status_change',
    message: 'Status changed to Blocked on "Health & Safety Guidelines"',
    taskId: '6',
    taskTitle: 'Health & Safety Guidelines',
    read: true,
    createdAt: '2024-03-03T13:10:00Z',
  },
  {
    id: '5',
    type: 'deadline',
    message: 'Task "Summer Program Budget Review" is overdue',
    taskId: '8',
    taskTitle: 'Summer Program Budget Review',
    read: false,
    createdAt: '2024-03-09T00:00:00Z',
  },
]

export const mockDashboardStats: DashboardStats = {
  myTasks: 5,
  overdueTasks: 2,
  completedThisWeek: 3,
  tasksByStatus: {
    'todo': 1,
    'in-progress': 3,
    'review': 2,
    'completed': 1,
    'blocked': 1,
  },
}

export const mockTaskHistory: TaskHistory[] = [
  {
    id: '1',
    taskId: '1',
    action: 'Task created',
    userId: '1',
    userName: 'Sarah Johnson',
    timestamp: '2024-02-20T10:00:00Z',
  },
  {
    id: '2',
    taskId: '1',
    action: 'Assigned to Michael Chen',
    userId: '1',
    userName: 'Sarah Johnson',
    timestamp: '2024-02-20T10:05:00Z',
  },
  {
    id: '3',
    taskId: '1',
    action: 'Status changed',
    userId: '2',
    userName: 'Michael Chen',
    timestamp: '2024-03-01T14:30:00Z',
    changes: {
      status: { old: 'To Do', new: 'In Progress' },
    },
  },
  {
    id: '4',
    taskId: '1',
    action: 'Moved to Initial Review',
    userId: '2',
    userName: 'Michael Chen',
    timestamp: '2024-03-01T14:30:00Z',
  },
]
